# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'gui.ui'
#
# Created: Thu Jun 21 21:25:49 2012
#      by: PyQt4 UI code generator 4.9.1
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    _fromUtf8 = lambda s: s

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName(_fromUtf8("MainWindow"))
        MainWindow.resize(998, 600)
        self.centralwidget = QtGui.QWidget(MainWindow)
        self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
        self.horizontalLayout_3 = QtGui.QHBoxLayout(self.centralwidget)
        self.horizontalLayout_3.setObjectName(_fromUtf8("horizontalLayout_3"))
        self.groupMySongs = QtGui.QGroupBox(self.centralwidget)
        self.groupMySongs.setObjectName(_fromUtf8("groupMySongs"))
        self.verticalLayout = QtGui.QVBoxLayout(self.groupMySongs)
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.tableWidgetMySongs = QtGui.QTableWidget(self.groupMySongs)
        self.tableWidgetMySongs.setAcceptDrops(False)
        self.tableWidgetMySongs.setAutoFillBackground(False)
        self.tableWidgetMySongs.setDragEnabled(False)
        self.tableWidgetMySongs.setDragDropOverwriteMode(False)
        self.tableWidgetMySongs.setDragDropMode(QtGui.QAbstractItemView.NoDragDrop)
        self.tableWidgetMySongs.setDefaultDropAction(QtCore.Qt.IgnoreAction)
        self.tableWidgetMySongs.setAlternatingRowColors(True)
        self.tableWidgetMySongs.setSelectionMode(QtGui.QAbstractItemView.ExtendedSelection)
        self.tableWidgetMySongs.setSelectionBehavior(QtGui.QAbstractItemView.SelectRows)
        self.tableWidgetMySongs.setShowGrid(False)
        self.tableWidgetMySongs.setCornerButtonEnabled(False)
        self.tableWidgetMySongs.setRowCount(0)
        self.tableWidgetMySongs.setColumnCount(4)
        self.tableWidgetMySongs.setObjectName(_fromUtf8("tableWidgetMySongs"))
        item = QtGui.QTableWidgetItem()
        self.tableWidgetMySongs.setHorizontalHeaderItem(0, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidgetMySongs.setHorizontalHeaderItem(1, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidgetMySongs.setHorizontalHeaderItem(2, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidgetMySongs.setHorizontalHeaderItem(3, item)
        self.tableWidgetMySongs.horizontalHeader().setVisible(True)
        self.tableWidgetMySongs.horizontalHeader().setCascadingSectionResizes(False)
        self.tableWidgetMySongs.horizontalHeader().setDefaultSectionSize(100)
        self.tableWidgetMySongs.horizontalHeader().setMinimumSectionSize(100)
        self.tableWidgetMySongs.horizontalHeader().setSortIndicatorShown(False)
        self.tableWidgetMySongs.horizontalHeader().setStretchLastSection(True)
        self.tableWidgetMySongs.verticalHeader().setCascadingSectionResizes(False)
        self.tableWidgetMySongs.verticalHeader().setDefaultSectionSize(30)
        self.tableWidgetMySongs.verticalHeader().setSortIndicatorShown(False)
        self.tableWidgetMySongs.verticalHeader().setStretchLastSection(False)
        self.verticalLayout.addWidget(self.tableWidgetMySongs)
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.pushButton_Add1 = QtGui.QPushButton(self.groupMySongs)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(_fromUtf8("icons/Button-Add-icon.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_Add1.setIcon(icon)
        self.pushButton_Add1.setObjectName(_fromUtf8("pushButton_Add1"))
        self.horizontalLayout.addWidget(self.pushButton_Add1)
        self.pushButton_Delete1 = QtGui.QPushButton(self.groupMySongs)
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(_fromUtf8("icons/Button-Close-icon.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_Delete1.setIcon(icon1)
        self.pushButton_Delete1.setObjectName(_fromUtf8("pushButton_Delete1"))
        self.horizontalLayout.addWidget(self.pushButton_Delete1)
        self.pushButton_Shuffle1 = QtGui.QPushButton(self.groupMySongs)
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(_fromUtf8("icons/Button-Refresh-icon.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_Shuffle1.setIcon(icon2)
        self.pushButton_Shuffle1.setObjectName(_fromUtf8("pushButton_Shuffle1"))
        self.horizontalLayout.addWidget(self.pushButton_Shuffle1)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.horizontalLayout_3.addWidget(self.groupMySongs)
        self.groupHerSongs = QtGui.QGroupBox(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupHerSongs.sizePolicy().hasHeightForWidth())
        self.groupHerSongs.setSizePolicy(sizePolicy)
        self.groupHerSongs.setObjectName(_fromUtf8("groupHerSongs"))
        self.verticalLayout_2 = QtGui.QVBoxLayout(self.groupHerSongs)
        self.verticalLayout_2.setObjectName(_fromUtf8("verticalLayout_2"))
        self.tableWidgetHerSongs = QtGui.QTableWidget(self.groupHerSongs)
        self.tableWidgetHerSongs.setAcceptDrops(False)
        self.tableWidgetHerSongs.setAutoFillBackground(False)
        self.tableWidgetHerSongs.setDragEnabled(False)
        self.tableWidgetHerSongs.setDragDropOverwriteMode(False)
        self.tableWidgetHerSongs.setDragDropMode(QtGui.QAbstractItemView.NoDragDrop)
        self.tableWidgetHerSongs.setDefaultDropAction(QtCore.Qt.IgnoreAction)
        self.tableWidgetHerSongs.setAlternatingRowColors(True)
        self.tableWidgetHerSongs.setSelectionMode(QtGui.QAbstractItemView.ExtendedSelection)
        self.tableWidgetHerSongs.setSelectionBehavior(QtGui.QAbstractItemView.SelectRows)
        self.tableWidgetHerSongs.setShowGrid(False)
        self.tableWidgetHerSongs.setCornerButtonEnabled(False)
        self.tableWidgetHerSongs.setRowCount(0)
        self.tableWidgetHerSongs.setColumnCount(4)
        self.tableWidgetHerSongs.setObjectName(_fromUtf8("tableWidgetHerSongs"))
        item = QtGui.QTableWidgetItem()
        self.tableWidgetHerSongs.setHorizontalHeaderItem(0, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidgetHerSongs.setHorizontalHeaderItem(1, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidgetHerSongs.setHorizontalHeaderItem(2, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidgetHerSongs.setHorizontalHeaderItem(3, item)
        self.tableWidgetHerSongs.horizontalHeader().setVisible(True)
        self.tableWidgetHerSongs.horizontalHeader().setCascadingSectionResizes(False)
        self.tableWidgetHerSongs.horizontalHeader().setDefaultSectionSize(100)
        self.tableWidgetHerSongs.horizontalHeader().setMinimumSectionSize(100)
        self.tableWidgetHerSongs.horizontalHeader().setSortIndicatorShown(False)
        self.tableWidgetHerSongs.horizontalHeader().setStretchLastSection(True)
        self.tableWidgetHerSongs.verticalHeader().setCascadingSectionResizes(False)
        self.tableWidgetHerSongs.verticalHeader().setDefaultSectionSize(30)
        self.tableWidgetHerSongs.verticalHeader().setSortIndicatorShown(False)
        self.tableWidgetHerSongs.verticalHeader().setStretchLastSection(False)
        self.verticalLayout_2.addWidget(self.tableWidgetHerSongs)
        self.horizontalLayout_2 = QtGui.QHBoxLayout()
        self.horizontalLayout_2.setObjectName(_fromUtf8("horizontalLayout_2"))
        self.pushButton_Add2 = QtGui.QPushButton(self.groupHerSongs)
        self.pushButton_Add2.setIcon(icon)
        self.pushButton_Add2.setObjectName(_fromUtf8("pushButton_Add2"))
        self.horizontalLayout_2.addWidget(self.pushButton_Add2)
        self.pushButton_Delete2 = QtGui.QPushButton(self.groupHerSongs)
        self.pushButton_Delete2.setIcon(icon1)
        self.pushButton_Delete2.setObjectName(_fromUtf8("pushButton_Delete2"))
        self.horizontalLayout_2.addWidget(self.pushButton_Delete2)
        self.pushButton_Shuffle2 = QtGui.QPushButton(self.groupHerSongs)
        self.pushButton_Shuffle2.setIcon(icon2)
        self.pushButton_Shuffle2.setObjectName(_fromUtf8("pushButton_Shuffle2"))
        self.horizontalLayout_2.addWidget(self.pushButton_Shuffle2)
        self.verticalLayout_2.addLayout(self.horizontalLayout_2)
        self.horizontalLayout_3.addWidget(self.groupHerSongs)
        self.verticalLayout_5 = QtGui.QVBoxLayout()
        self.verticalLayout_5.setObjectName(_fromUtf8("verticalLayout_5"))
        self.pushButton_Save = QtGui.QToolButton(self.centralwidget)
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(_fromUtf8("icons/Save-icon.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_Save.setIcon(icon3)
        self.pushButton_Save.setIconSize(QtCore.QSize(128, 128))
        self.pushButton_Save.setToolButtonStyle(QtCore.Qt.ToolButtonIconOnly)
        self.pushButton_Save.setObjectName(_fromUtf8("pushButton_Save"))
        self.verticalLayout_5.addWidget(self.pushButton_Save)
        spacerItem = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout_5.addItem(spacerItem)
        self.horizontalLayout_3.addLayout(self.verticalLayout_5)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtGui.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 998, 24))
        self.menubar.setObjectName(_fromUtf8("menubar"))
        self.menuAbout = QtGui.QMenu(self.menubar)
        self.menuAbout.setObjectName(_fromUtf8("menuAbout"))
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtGui.QStatusBar(MainWindow)
        self.statusbar.setObjectName(_fromUtf8("statusbar"))
        MainWindow.setStatusBar(self.statusbar)
        self.actionAbout = QtGui.QAction(MainWindow)
        self.actionAbout.setObjectName(_fromUtf8("actionAbout"))
        self.menuAbout.addAction(self.actionAbout)
        self.menubar.addAction(self.menuAbout.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(QtGui.QApplication.translate("MainWindow", "Music Blender", None, QtGui.QApplication.UnicodeUTF8))
        self.groupMySongs.setTitle(QtGui.QApplication.translate("MainWindow", "My songs", None, QtGui.QApplication.UnicodeUTF8))
        self.tableWidgetMySongs.setSortingEnabled(False)
        item = self.tableWidgetMySongs.horizontalHeaderItem(0)
        item.setText(QtGui.QApplication.translate("MainWindow", "Title", None, QtGui.QApplication.UnicodeUTF8))
        item = self.tableWidgetMySongs.horizontalHeaderItem(1)
        item.setText(QtGui.QApplication.translate("MainWindow", "Artist", None, QtGui.QApplication.UnicodeUTF8))
        item = self.tableWidgetMySongs.horizontalHeaderItem(2)
        item.setText(QtGui.QApplication.translate("MainWindow", "Size", None, QtGui.QApplication.UnicodeUTF8))
        item = self.tableWidgetMySongs.horizontalHeaderItem(3)
        item.setText(QtGui.QApplication.translate("MainWindow", "Path", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton_Add1.setText(QtGui.QApplication.translate("MainWindow", "Add", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton_Delete1.setText(QtGui.QApplication.translate("MainWindow", "Delete", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton_Shuffle1.setText(QtGui.QApplication.translate("MainWindow", "Shuffle", None, QtGui.QApplication.UnicodeUTF8))
        self.groupHerSongs.setTitle(QtGui.QApplication.translate("MainWindow", "His/Her songs", None, QtGui.QApplication.UnicodeUTF8))
        self.tableWidgetHerSongs.setSortingEnabled(False)
        item = self.tableWidgetHerSongs.horizontalHeaderItem(0)
        item.setText(QtGui.QApplication.translate("MainWindow", "Title", None, QtGui.QApplication.UnicodeUTF8))
        item = self.tableWidgetHerSongs.horizontalHeaderItem(1)
        item.setText(QtGui.QApplication.translate("MainWindow", "Artist", None, QtGui.QApplication.UnicodeUTF8))
        item = self.tableWidgetHerSongs.horizontalHeaderItem(2)
        item.setText(QtGui.QApplication.translate("MainWindow", "Size", None, QtGui.QApplication.UnicodeUTF8))
        item = self.tableWidgetHerSongs.horizontalHeaderItem(3)
        item.setText(QtGui.QApplication.translate("MainWindow", "Path", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton_Add2.setText(QtGui.QApplication.translate("MainWindow", "Add", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton_Delete2.setText(QtGui.QApplication.translate("MainWindow", "Delete", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton_Shuffle2.setText(QtGui.QApplication.translate("MainWindow", "Shuffle", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton_Save.setText(QtGui.QApplication.translate("MainWindow", "Merge lists", None, QtGui.QApplication.UnicodeUTF8))
        self.menuAbout.setTitle(QtGui.QApplication.translate("MainWindow", "Help", None, QtGui.QApplication.UnicodeUTF8))
        self.actionAbout.setText(QtGui.QApplication.translate("MainWindow", "About", None, QtGui.QApplication.UnicodeUTF8))

